name: Development to Staging

on:
  pull_request:
    branches:
      - 'staging'

jobs:
  my_first_job:
    name: Is origin development branch?
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check branch name
        run: |
          if [[ "${{ github.head_ref }}" == "development" ]]; then
            echo "Correct origin branch"
          else
            echo "Incorrect origin branch, pull request must go through the development branch before entering the staging branch" 
            exit 1
          fi
