name: Check Branch Naming Conventions

on:
  pull_request:
    branches:
      - main

jobs:
  my_first_job:
    name: Checking if branch naming convention is successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check branch name
        if: contains(github.ref, '${{ github.actor }}-')
        run: echo "Branch has correct naming conventions"
          echo ${{ github.head_ref }} ${{ github.actor }}

  my_second_job:
    name: Checking if branch naming convention is un-successful
    if: failure()
    runs-on: ubuntu-latest
    needs: my_first_job
    steps:
      - uses: actions/checkout@v4
      - name: Naming convention Failure
        run: echo "Incorrect naming convention, branches must contain username" && exit 1
